"""notifications

Revision ID: 35c5d06b06ae
Revises: df9ad5f81e88
Create Date: 2019-10-13 18:39:54.416753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c5d06b06ae'
down_revision = 'df9ad5f81e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nofications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timesetamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nofications_name'), 'nofications', ['name'], unique=False)
    op.create_index(op.f('ix_nofications_timesetamp'), 'nofications', ['timesetamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nofications_timesetamp'), table_name='nofications')
    op.drop_index(op.f('ix_nofications_name'), table_name='nofications')
    op.drop_table('nofications')
    # ### end Alembic commands ###
