"""fix notifications

Revision ID: 53335055ab8d
Revises: d9cb16cf6355
Create Date: 2019-10-13 18:56:40.249205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53335055ab8d'
down_revision = 'd9cb16cf6355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('timestamp', sa.Float(), nullable=True))
    op.create_index(op.f('ix_notification_timestamp'), 'notification', ['timestamp'], unique=False)
    op.drop_index('ix_notification_timesetamp', table_name='notification')
    op.drop_column('notification', 'timesetamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('timesetamp', sa.FLOAT(), nullable=True))
    op.create_index('ix_notification_timesetamp', 'notification', ['timesetamp'], unique=False)
    op.drop_index(op.f('ix_notification_timestamp'), table_name='notification')
    op.drop_column('notification', 'timestamp')
    # ### end Alembic commands ###
