"""fix notifications

Revision ID: d9cb16cf6355
Revises: 35c5d06b06ae
Create Date: 2019-10-13 18:51:20.358099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9cb16cf6355'
down_revision = '35c5d06b06ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timesetamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_name'), 'notification', ['name'], unique=False)
    op.create_index(op.f('ix_notification_timesetamp'), 'notification', ['timesetamp'], unique=False)
    op.drop_index('ix_nofications_name', table_name='nofications')
    op.drop_index('ix_nofications_timesetamp', table_name='nofications')
    op.drop_table('nofications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nofications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('timesetamp', sa.FLOAT(), nullable=True),
    sa.Column('payload_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nofications_timesetamp', 'nofications', ['timesetamp'], unique=False)
    op.create_index('ix_nofications_name', 'nofications', ['name'], unique=False)
    op.drop_index(op.f('ix_notification_timesetamp'), table_name='notification')
    op.drop_index(op.f('ix_notification_name'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
